version: '3.8'

services:
  backend:
    build:
      context: ./nest-backend
      dockerfile: Dockerfile
    command:  sh -c "npm run migration:create && npm run migration:up && npm run seed && npm run start:dev"
    container_name: datatys-backend
    restart: unless-stopped
    env_file:
      - nest-backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: datatys-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: datatys
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
